version: '3'
services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: root
    ports:
      - "5433:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "chown -R 1000:1000 /myapp/config && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      SECRET_KEY_BASE: your_generated_key
      ANIMEMORY_DATABASE_PASSWORD: password
    platform: linux/amd64
